### ISSUE TITLE
Livecut has no name field specified in it's vst3 spec so it appears in an blank folder

### ISSUE THREAD

**Issue by nykwil** [scheffle/Livecut#1]
This is just a nitpick, I attached a screenshot on how it appears in Ableton. If someone pointed me in the right direction I could make a pull request.

I just want to say how awesome it is that you made this. I am eternally grateful.

![image](https://user-images.githubusercontent.com/1003128/167453064-247cbe18-6952-4dbc-b929-e4c8293b78b0.png)

**Comment by nykwil** [comment]
https://github.com/scheffle/Livecut/pull/2 Pull request, again just a  nitpick.

**Comment by scheffle** [comment]
Done with #2
