### ISSUE TITLE
Add -DCMAKE_BUILD_TYPE to cmake commands

### ISSUE THREAD

**Issue by eventual-recluse** [scheffle/Livecut#3]
Build type had to be specified with cmake to build successfully.

i.e.:

cmake -Dvst3sdk_SOURCE_DIR=$PATH_TO_THE_VST3_SDK  ../VST3/ -DCMAKE_BUILD_TYPE=RELEASE .

PS This plugin is fantastic. Thanks for the working VST3 version without juce. Tested on linux and it's working fine here.

**Comment by Andreya-Autumn** [comment]
Hey there! With some help from my friends, I eventually also figured this out. I'm wondering if anyone has gotten a functioning 64bit MacOS VST3 using this method? I've gotten zsh to seemingly go through the build process, but with lots of warning flags everywhere. And no .vst3 file shows up in the end. 

Any help appreciated!

**Comment by eventual-recluse** [comment]
Hi! Did you get   "[100%] Built target Livecut"   at the end of the build process? If it built successfuly the plugin should appear in:

build/VST3/RELEASE/Livecut.vst3

(presuming the build type was RELEASE)

The plugin is that Livecut.vst3 folder with all its contents. On my system the build process automatically links it to the default vst3 folder so I didn't need to install it myself.

If you're looking for it in a host application, there's no creator/author defined, so it might appear under a blank folder or 'unknown' in the plugin list.

Good luck!
